#    Copyright 2020, 2021, 2024 CodeMerx
#    This file is part of CodemerxDecompile.

#    CodemerxDecompile is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.

#    CodemerxDecompile is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU Affero General Public License for more details.

#    You should have received a copy of the GNU Affero General Public License
#    along with CodemerxDecompile.  If not, see<https://www.gnu.org/licenses/>.

name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-on-windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4

    - name: Setup DotNet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          2.x
          3.x
          5.x
          6.x
          7.x

    - name: Run Tests
      run: dotnet test -c Release
      working-directory: ./src/Decompiler.Tests
  
  test-on-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          7.x

    - name: Run Tests
      run: dotnet test -c Release
      working-directory: ./src/Decompiler.Tests

  test-on-mac:
    runs-on: macos-13

    env:
      DOTNET_INSTALL_DIR: "/usr/local/share/dotnet"

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.x
          7.x

    - name: Run Tests
      run: dotnet test -c Release
      working-directory: ./src/Decompiler.Tests
